spring.application.name=demo-cac-chuc-nang-cho-code-web
# Cấu hình kết nối cơ sở dữ liệu
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=123456
# Cấu hình JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
# Cấu hình H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# Cấu hình ẩn
spring.config.import=optional:application-private.properties

# 1. Kích hoạt JDBC Session
spring.session.store-type=jdbc

# 2. Ép buộc tạo bảng từ file schema của thư viện
spring.session.jdbc.initialize-schema=always

# 3. QUAN TRỌNG: Cấu hình này giúp Spring tìm thấy file schema.sql mặc định của hệ thống
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# Chỉ định rõ ràng là dùng schema của H2 để Spring Session tìm đúng file
spring.session.jdbc.schema=classpath:org/springframework/session/jdbc/schema-h2.sql

