spring.application.name=demo-cac-chuc-nang-cho-code-web
# Cấu hình kết nối cơ sở dữ liệu
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=123456
# Cấu hình JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
# Cấu hình H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# Cấu hình ẩn
spring.config.import=optional:application-private.properties
